const local = {
    en: {
        day: "day",
        days: "days",
        hour: "hour",
        hours: "hours",
        minute: "minute",
        minutes: "minutes",
        second: "second",
        seconds: "seconds",
        top: "This is how much Jeff Bezos made...",
        bottom: "...since you started reading this page.",
        link: "See how this number was calculated",
        changeLight: "Change to light mode",
        changeDark: "Change to dark mode",
        messages: {
            "15000": "more than a minimum wage worker... in a year",
            "31200": "more than Amazon's lowest paid employee... in a year",
            "47000": "more than the median yearly salary in the United States",
            "63409": "more than the average yearly salary in the United States",
            "81840": "more than his own yearly salary!",
            "99000": "enough not to qualify for covid-19 stimulus checks",
            "116600": "more than the yearly salary of a Sr Software Developer",
            "142000": "enough to buy a 'basic' Aston Martin Vantage",
            "174000": "more than what a US Senator makes in a year",
            "182000": "enough to buy a fully loaded Tesla Model S",
            "250000": "enough to raise a child from birth to age 17",
            "295300": "enough to buy a house for the median price in the USA",
            "320000": "more than the yearly salary of 99% of the US population",
            "400000": "more than what the US President makes in a year",
            "538926": "more than the annual income of the US 1%",
            "916000": "more than the median cost of a Manhattan apartment",
            "1000000": "enough to pay for the most expensive fishing lure ever",
            "1500000": "more than the annual income of the US 0.1%",
            "2029612": "enough to pay for a house in Hollywood, CA",
            "7000000": "more than the annual income of the US 0.01%",
            "69346250": "more than the most expensive NFT",
            "81000000": "more than the cost of a seat to space"
        }
    },
    es: {
        day: "d&iacute;a",
        days: "d&iacute;as",
        hour: "hora",
        hours: "horas",
        minute: "minuto",
        minutes: "minutos",
        second: "segundo",
        seconds: "segundos",
        top: "Esto es lo que gan&oacute; Jeff Bezos...",
        bottom: "...desde que entraste en esta p&aacute;gina.",
        link: "Lee sobre c&oacute;mo se calcul&oacute; ese n&uacute;mero",
        changeLight: "Cambiar a modo d&iacute;a",
        changeDark: "Cambiar a modo noche",
        messages: {
            "15000": "m&aacute;s que el salario m&iacute;nimo interprofesional en EE.UU.",
            "31200": "m&aacute;s que el trabajador que menos cobra en Amazon... en un a&ntilde;o",
            "47000": "m&aacute;s que la mediana salarial en los Estados Unidos",
            "63409": "m&aacute;s que la media salarial en los Estados Unidos",
            "81840": "m&aacute;s que su propio sueldo anual",
            "99000": "suficiente para no recibir los cheques del estimulo de la covid-19",
            "116600": "m&aacute;s que el salario de un Programador Senior en los EE.UU.",
            "142000": "suficiente para comprar un Aston Martin Vantage",
            "174000": "m&aacute;s que el salario anual de un Senador de los EE.UU.",
            "182000": "suficiente para comprar un Tesla modelo S con todos los extras",
            "250000": "suficiente para criar un ni&ntilde;o en los Estados Unidos hasta que cumpla los 18",
            "295300": "suficiente para comparar una casa al precio medio en los EE.UU. ",
            "320000": "m&aacute;s que el salario del 99% de la poblaci&oacute;n de los EE.UU.",
            "400000": "m&aacute;s que el sueldo anual del Presidente de los Estados Unidos",
            "538926": "m&aacute;s que los ingresos anuales del 1% m&aacute;s rico de EE.UU.",
            "916000": "m&aacute;s que el precio medio de un apartamento en Manhattan",
            "1000000": "suficiente para pagar por el anzuelo m&aacute;s caro del mundo",
            "1500000": "m&aacute;s que los ingresos anuales del 0.1% m&aacute;s rico de EE.UU.",
            "2029612": "suficiente para comprar una mansi&oacute;n en Hollywood",
            "7000000": "m&aacute;s que los ingresos anuales del 0.01% m&aacute;s rico de EE.UU.",
            "69346250": "suficiente para pagar el NFT m&aacute;s caro",
            "81000000": "m&aacute;s que el precio de un viaje al espacio"
        }
    },
    ru: {
        day: "день",
        days: "дня",
        hour: "час",
        hours: "ч.",
        minute: "минута",
        minutes: "мин.",
        second: "сек.",
        seconds: "сек.",
        top: "Столько заработал Джефф Безос...",
        bottom: "...с того момента, как Вы открыли эту страницу.",
        link: "Как это посчитали?",
        changeLight: "Светлая тема",
        changeDark: "Темная тема",
        messages: {
            "15000": "больше, чем зарабатывает в США рабочий с минимальным окладом... за целый год",
            "31200": "больше, чем сотрудник Amazon с самой низкой зарплатой... за целый год",
            "47000": "больше медианного годового оклада в США",
            "63409": "больше среднего годового оклада в США",
            "81840": "больше, чем годовой оклад самого Джеффа Безоса!",
            "99000": "зарабатывая столько, в США нельзя претендовать на поддерживающие выплаты в связи с коронавирусом",
            "116600": "больше годового оклада старшего разработчика программного обеспечения в США",
            "142000": "хватит, чтобы купить Aston Martin Vantage в базовой комплектации",
            "174000": "больше, чем зарабатывает сенатор США за целый год",
            "182000": "хватит на покупку полностью оснащенной Tesla Model S",
            "250000": "достаточно, чтобы в США вырастить ребенка до возраста 17 лет",
            "295300": "хватит на покупку дома в США по медианной цене",
            "320000": "больше годового оклада 99% населения США",
            "400000": "больше, чем зарабатывает президент США за целый год",
            "538926": "больше, чем годовой доход, позволяющий войти в число 1% наиболее богатых жителей США",
            "916000": "больше медианной цены квартиры на Манхэттене",
            "1000000": "хватит, чтобы купить самую дорогую в мире наживку для рыбалки",
            "1500000": "больше, чем годовой доход, позволяющий войти в число 0,1% наиболее богатых жителей США",
            "2029612": "хватит, чтобы купить дом в Голливуде",
            "7000000": "больше, чем годовой доход, позволяющий войти в число 0,01% наиболее богатых жителей США",
            "69346250": "больше, чем стоит самый дорогой NFT-токен",
            "81000000": "больше, чем стоит место на космическом корабле"
        }
    },
    hi: {
        day: "दिन",
        days: "दिन",
        hour: "घंटा",
        hours: "घंटे",
        minute: "मिनट",
        minutes: "मिनट",
        second: "सेकंड",
        top: "जेफ बेजोस ने इतना कमाया...",
        bottom: "... जब से आपने इस पेज को पढ़ना शुरू किया है।",
        link: "देखें कि इस संख्या की गणना कैसे की गई",
        changeLight: "लाइट मोड में बदलें",
        changeDark: "डार्क मोड में बदलें",
        messages: {
            "15000": "एक वर्ष में न्यूनतम वेतन कर्मी से अधिक...",
            "31200": "एक साल में Amazon के सबसे कम वेतन पाने वाले कर्मचारी से भी ज्यादा",
            "47000": "संयुक्त राज्य में औसत वार्षिक वेतन से अधिक",
            "63409": "संयुक्त राज्य में औसत वार्षिक वेतन से अधिक",
            "81840": "अपने स्वयं के वार्षिक वेतन से अधिक!",
            "99000": "कोविड -19 प्रोत्साहन जांच के लिए अर्हता प्राप्त करने के लिए पर्याप्त नहीं है",
            "116600": "वरिष्ठ सॉफ्टवेयर डेवलपर के वार्षिक वेतन से अधिक",
            "142000": "एक 'बेसिक' एस्टन मार्टिन वैंटेज खरीदने के लिए पर्याप्त",
            "174000": "एक अमेरिकी सीनेटर एक वर्ष में जितना कमाता है उससे अधिक",
            "182000": "पूरी तरह से भरी हुई टेस्ला मॉडल एस खरीदने के लिए पर्याप्त",
            "250000": "जन्म से १७ वर्ष की आयु तक बच्चे को पालने के लिए पर्याप्त",
            "95300": "संयुक्त राज्य अमेरिका में औसत कीमत के लिए एक घर खरीदने के लिए पर्याप्त",
            "320000": "अमेरिका की आबादी के 99% के वार्षिक वेतन से अधिक",
            "400000": "अमेरिकी राष्ट्रपति एक वर्ष में जितना कमाते हैं उससे अधिक",
            "538926": "अमेरिका की वार्षिक आय 1% से अधिक",
            "916000": "मैनहट्टन अपार्टमेंट की औसत लागत से अधिक",
            "1000000": "अब तक के सबसे महंगे मछली पकड़ने के लालच के लिए भुगतान करने के लिए पर्याप्त",
            "1500000": "यू.एस. की वार्षिक आय 0.1% से अधिक",
            "2029612": "हॉलीवुड, CA में एक घर के लिए भुगतान करने के लिए पर्याप्त",
            "7000000": "यू.एस. की वार्षिक आय 0.01% से अधिक",
            "69346250": "सबसे महंगे एनएफटी से अधिक",
            "81000000": "अंतरिक्ष के लिए एक सीट की लागत से अधिक"
        }
    }

};